### ISSUE TITLE
why save data to firebase, not local?

### ISSUE THREAD

**Issue by baryon** [wavesplatform/WavesWallet-iOS#34]
- is not security problem?
- when disconnected status, you can't use wallet

**Comment by mefilt** [comment]
Hi, in v2.0, the application can be used only with the Internet. 
In "Firebase" we do not store "Seed" and "Password" from your wallet.
"Firebase" is used to avoid brute force passcode
Sorry for the long answer. :)

**Comment by bianxiang** [comment]
how to remove firebase from this project safely，because I am in China，can not connect to google......

**Comment by bianxiang** [comment]
Because some area can not connect to firebase，such as China，cannot connect to Google ，I changed firebase to local database by RealmSwift，base on version 2.5，language :Swift，see this url of iOS：
👉[https://github.com/bianxiang/WavesWallet-iOS-FirebaseRemoved](https://github.com/bianxiang/WavesWallet-iOS-FirebaseRemoved)
